architect/functions

src/events/_publish.js
src/queues/_publish.js

See also: https://github.com/arc-repos/architect/pull/225

Add path to sandbox requests for @queues/@events

---

changelog.md
src/proxy/read.js

...  for config-reduced proxy reads

Adds ARC_STATIC_BUCKET + ARC_STATIC_FOLDER env vars

---

src/http/proxy/public.js

config is optional

---

changelog.md
src/http/_res-fmt.js
src/http/async/index.js
src/http/http.js
test/unit/src/http/http-req-fixtures.js
test/unit/src/http/http-req-test.js
test/unit/src/http/http-res-test.js

Fixes proxy responses

---

changelog.md
src/http/_res-fmt.js
test/unit/src/http/http-res-test.js

Fixed minor issue in `ARC_HTTP` env var check

---

changelog.md
src/http/proxy/read.js
src/http/proxy/response.js
src/http/proxy/sandbox.js

Fixes issue where binary assets delivered through `sandbox` may not be properly encoded

---

changelog.md
src/http/_res-fmt.js
src/http/proxy/response.js

Proxy encoding

---

changelog.md
src/http/proxy/sandbox.js

Adds check for Arc static folder in Sandbox proxy

---

src/http/proxy/public.js
src/http/proxy/read.js
src/http/proxy/response.js
src/http/proxy/sandbox.js

Restores proxy config (bucket, bucket.folder, cacheControl), fixes SPA HTML responses

---

src/tables/doc.js

Temp fix for local repl calls

---

changelog.md
package-lock.json
src/http/proxy/read.js
src/http/proxy/response.js
src/http/proxy/sandbox.js
src/http/proxy/templatize.js
test/mock/project/public/publicfile.md
test/unit/src/http/proxy/read-test.js
test/unit/src/http/proxy/sandbox-test.js

Enable fingerprinting for proxy requests

---

changelog.md
src/http/proxy/read.js
test/unit/src/http/proxy/read-test.js

Changed static manifest loader to be more bundler friendly

---

src/http/proxy/sandbox.js

Fixes sandbox pathing for static manifest

---

changelog.md
src/http/_res-fmt.js
src/http/errors/index.js
src/http/proxy/public.js
src/http/proxy/read.js
src/http/proxy/sandbox.js
test/unit/src/http/proxy/public-test.js

Fixes broken response when bucket is not configured as root proxy; improves HTTP error states

---

changelog.md
src/http/_res-fmt.js
src/http/helpers/body-parser.js
src/http/proxy/response.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/helpers/body-parser-test.js
test/unit/src/http/http-res-fixtures.js
test/unit/src/http/http-res-test.js
test/unit/src/http/proxy/response-test.js

Adds anti-caching and body parsing for 'application/vnd.api+json', fixes #141

---

test/unit/src/http/http-req-fixtures.js
test/unit/src/http/http-req-test.js
test/unit/src/http/http-res-test.js
test/unit/src/http/proxy/public-test.js

Minor test refactor: /{proxy+} stuff does not belong in Arc 5 tests

---

changelog.md
package-lock.json
package.json
src/http/proxy/public.js
test/unit/src/http/proxy/public-test.js

this only effects `ARC_STATIC_SPA=false` code path; currently you have to specify full paths

adds default index.html to nested folders

---

changelog.md
src/static/index.js
test/unit/src/static/index-test.js

Throw error if asset not found by static helper, adds stagePath option

---

.github/workflows/build.yml
changelog.md
package-lock.json
package.json
src/ws/send.js

Uses updated WSS URL if available

---

changelog.md
src/events/subscribe.js

Provides fallback event object for direct invocation of event functions

---

changelog.md
src/events/publish-old.js
src/events/publish-sandbox.js
src/http/session/providers/ddb/_get-dynamo-doc-instance.js
src/queues/publish-old.js
src/queues/publish-sandbox.js
src/tables/db.js
src/tables/doc.js

Adds support for running multiple Sandboxes at the same time

---

changelog.md
src/tables/dynamo.js

Fixes issue that caused Sandbox to stall when called via the Architect CLI

---

changelog.md
src/tables/dynamo.js

Improve DynamoDB interface predicates to account for certain test harnesses

---

package.json
src/index.js
src/tables/dynamo.js
src/tables/index.js

Additional DynamoDB predicate fixes

---

src/http/proxy/public.js
src/http/proxy/read.js
test/unit/src/http/proxy/read-test.js

wip, would like to get this on mainline quickly so we can migrate http apis

prepare for http apis

---

changelog.md
src/http/_res-fmt.js

No longer send newline with empty body; fixes #254

---

changelog.md
src/tables/index.js

Fix local predicate for arc.tables

---

changelog.md
src/tables/factory.js

Fix `arc.tables._name` calls, ht @filmaj

---

test/unit/src/tables/factory-test.js

This PR will fail without #265 - but will fail on current master. These tests pass with #265. FYI @ryanblock

adding tests for tables.factory

---

src/http/proxy/read.js
test/unit/src/http/proxy/read-test.js

Content encoding

---

changelog.md
src/http/_res-fmt.js
test/unit/src/http/http-res-test.js

Fixes backward compat for legacy old school tidy Arc response params

---

src/events/publish-old.js
src/events/publish-sandbox.js
src/queues/publish-old.js
src/queues/publish-sandbox.js

Return errors on local @events + @queues publishing

---

.gitignore
changelog.md
package.json
src/http/async/index.js
src/http/http.js
src/http/session/providers/ddb/find.js
src/http/session/providers/ddb/get-idx.js
src/http/session/providers/ddb/index.js
src/http/session/providers/ddb/update.js
test/integration/ddb-session-test.js
test/mock/mock-arc
test/mock/mock-arc-fingerprint
test/mock/project/.arc
test/mock/project/src/http/get-http_async_session/index.js
test/mock/project/src/http/get-http_session/index.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-res-test.js
test/unit/src/http/session/get-idx-test.js

Cookie param and session fixes

---

changelog.md
src/http/helpers/params.js
test/unit/src/http/async/index-req-test.js
test/unit/src/http/http-req-test.js

Restore req.path param to HTTP APIs

---

changelog.md
src/events/publish-old.js
src/events/publish-topic.js
src/queues/publish-old.js

Removed unnecessary console logging

---

.github/code_of_conduct.md
.github/pull_request_template.md
_changelog.md
contributing.md
readme.md

docs: rename master to main

---

test/integration/ddb-session-test.js
test/integration/jwe-session-test.js
test/unit/src/http/session/session-test.js

chore: cleanup cwd usage

---

_changelog.md
package.json
readme.md
src/index.js

Update deps, changelog, and readme

---

_changelog.md
src/ws/index.js

fix: crash when no ARC_WSS_URL is set

---

_changelog.md
src/tables/dynamo.js

Fail gracefully in Architect 10+ / Sandbox 5+

---

_changelog.md
package.json
src/http/helpers/body-parser.js
test/unit/src/http/helpers/body-parser-test.js

Body parser

---

_changelog.md
package.json
src/discovery/index.js
src/events/publish.js
src/http/session/providers/ddb/create.js
src/http/session/providers/ddb/find.js
src/http/session/providers/ddb/index.js
src/http/session/providers/ddb/update.js
src/tables/dynamo.js
src/tables/index.js
src/ws/index.js
test/unit/src/tables/dynamo-test.js

Improve coldstart by up to 30x

---

src/index.js
src/lib/version.js
test/integration/static-fingerprinted-test.js
test/integration/static-plain-test.js
test/integration/version-check.js
test/mock/project/app.arc
test/mock/project/src/http/get-incompatible_version/index.js
test/unit/src/discovery/index-test.js
test/unit/src/events/publish-test.js
test/unit/src/events/subscribe-test.js
test/unit/src/http/async/index-req-test.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-req-test.js
test/unit/src/http/http-res-test.js
test/unit/src/lib/version-test.js
test/unit/src/queues/publish-test.js
test/unit/src/queues/subscribe-test.js
test/unit/src/static/index-test.js

Props to @reconbot who originally authored this code (which got lost in the v5 refactor)
Thanks again!

Restore minimum required version check

---

_changelog.md
src/http/helpers/body-parser.js

Fix body parsing performance issue

---

_changelog.md
package.json
src/http/_res-fmt.js
test/unit/src/http/async/index-req-test.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-req-test.js
test/unit/src/http/http-res-test.js

Add brotli compression of string responses (if appropriate)

---

test/integration/ws-test.js
test/mock/project/.arc
test/mock/project/src/ws/connect/index.js
test/mock/project/src/ws/default/index.js
test/mock/project/src/ws/disconnect/index.js

chore: test websockets a bit

---

_changelog.md
src/events/publish.js

Ensure SNS/SQS are required only when needed

---

.gitignore
_changelog.md
package.json
src/http/_res-fmt.js
src/http/async/index.js
src/http/helpers/body-parser.js
src/http/helpers/csrf.js
src/http/helpers/params.js
src/http/http.js
src/http/session/providers/ddb/find.js
src/http/session/providers/ddb/index.js
src/http/session/providers/jwe.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-res-test.js

Assume `nodejs14.x` or higher

---

_changelog.md
src/tables/factory.js

Fix output of `tables.put()` to return the updated item, as in versions <=7; fixes #554

---

src/lib/index.js

See also https://github.com/architect/sandbox/pull/737.
Thanks again!

AWS access keys may not contain underscores
