architect/functions

src/http/helpers/_static.js

With the previous order, when running locally, `fs.readFileSync(arcFile)` will throw an error (since there is no `shared/.arc` on sandbox). Since we only use `arc` when not running locally this seems safe. But I'd love you to double check me here!

Don't crash trying to read shared/.arc when runningLocally

---

package-lock.json
package.json
src/http/helpers/_static.js

Fixes similar issue in `arc-functions` to `.arc` file path reading in `arc-data`, comments here: https://github.com/arc-repos/arc-data/pull/11#issue-244893756
This `arc-functions` fix published to NPM as `1.11.2@beta`
Similar `arc-data` fix now published to NPM as `2.0.11@beta`
---
Backup copy:
In the past we've had a number of concerns related to generating, placing, and retrieving `.arc` files in Functions, specifically with differentiations accounting for Function filesystem generation (i.e. `sandbox` vs. `deploy` vs. `hydrate`) and environments (`sandbox` vs. real Lambdas).
These have had an influence in how a Function's `.arc` file could be found by libraries such as `arc-data` and `arc-functions`.
Fortunately, this got dried up a lot recently, and is now much more deterministic due …

Fix static helper arc path

---

src/http/providers/ddb.js
src/http/providers/jwe.js
src/http/session/write.js

`Max-Age` attribute represents number of seconds until the cookie expires, not date of expiry [in milliseconds since epoch]. In modern browsers, because `Max-Age` supersedes `Expiry` – which is, presumably, being set as intended – cookies are set with expirations ridiculously far into the future (the year 76020, currently).

align cookie Expires/Max-Age attributes

---

src/queues/_publish.js

Fixes the conditional to honor `ARC_LOCAL` so that `arc.queues.publish` works as expected when running from `sandbox`.
Behavior is consistent with [arc.event.publish](https://github.com/arc-repos/arc-functions/blob/master/src/events/_publish.js#L60).

Minor fix: queue/publish local conditional

---

src/queues/_publish.js

For a project I'm working on we found a use-case for sending messages to queues with a timer (ref: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-send-message-with-timer.html).
I figure it's most user-friendly if we can simply pass `delaySeconds` on publish.
Not sure if an implementation for the local environment is necessary, so I've only added it to sqs-sendMessage.

Allow sending delaySeconds on queue publish

---

package.json
src/middleware/index.js
test/unit/middleware/index-test.js

Fixed middleware not working when deployed to lambda. Lambda request objects do not have a `method` property, only an `httpMethod` property. Request objects in sandbox has both. See architect/sandbox#17 for more discussion on the issue.
This closes #45.
✅ also added test for unmodified request passing in middleware.

🐛 fix for middleware functionality on lambda

---

changelog.md
src/http/session/providers/ddb/index.js
src/http/session/providers/jwe.js
test/unit/src/http/session/session-test.js

Session duration is currently hard-coded to one week. This change allows specifying a session duration (in seconds) in a SESSION_TTL environment variable. If no variable is passed, the default remains in place.

Allow setting session ttl via SESSION_TTL env var

---

changelog.md
package.json
src/static/index.js
test/unit/src/static/index-test.js

Calling `static()` with the root path returns `/_static/`

---

changelog.md
src/http/session/providers/ddb/index.js
src/http/session/providers/jwe.js
test/unit/src/http/session/session-test.js

In version 2, cookies are set in an array on request rather than a header. This change is backwards compatible with version 1.
Thanks again!

Fixed support for Lambda payload version 2 in session

---

src/http/helpers/url.js
test/unit/src/http/helpers/url-test.js

this yields the same behaviour as `arc.static`. also added unit tests for http.helpers.url
Thanks again!

have `arc.http.helpers.url` respect ARC_LOCAL flag

---

.gitignore
src/http/proxy/format/templatize.js

Hello all,
I'm currently working on a small package that adds the ability to deploy ReasonML/Bucklescript projects to Begin.com via architect.
This requires "bundling" of sorts; nothing crazy, just bog-standard tree-shaking. I'm currently unable to do this effectively when using the functions package as `static` is a reserved word that's being used as a variable name in a file.
This PR solely renames that variable; all tests pass.

Change reserved keyword variable name

---

readme.md
src/ws/index.js

- You pass `send` an object not a string for payload
- Readme was missing info on this function

docs: web socket documentation and jsdoc

---

.github/workflows/build.yml
src/http/session/providers/ddb/index.js
test/integration/ddb-session-test.js
test/unit/src/http/session/session-test.js

reading and writing ddb-backed sessions was a bit messed up, in a sandbox context we were using the wrong table names, need to be consistent in using logical ids for tables

re-enable full test runs in ci, fix ddb-backed sessions

---

changelog.md
src/tables/sandbox.js
test/unit/src/tables/sandbox-test.js

This fixes architect/architect#1111
Tho integration tests are disabled on this repo so I am wont to merge this 😞

Fix `tables()` not returning a client wrapper for any tables with the word "production" in their names

---

changelog.md
package.json
src/discovery/index.js
src/events/index.js
src/events/publish-topic.js
src/events/publish.js
src/index.js
src/queues/index.js
src/queues/publish-queue.js
src/queues/publish.js
src/tables/index.js
test/integration/ddb-session-test.js
test/unit/src/discovery/index-test.js
test/unit/src/events/publish-test.js
test/unit/src/queues/publish-test.js

This relates to the work described in the service discovery thread: https://github.com/architect/architect/issues/1091
The local-service-discovery component requires use in conjunction with this open sandbox pull request: https://github.com/architect/sandbox/pull/563/
I think I'd like to test this out all packaged together with a few other moving parts (`deploy`, `sandbox` and the docs) in a new minor version (RC release to start with) of architect.

arc.services service map and new service discovery

---

test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-res-test.js
test/unit/src/http/proxy/format/response-test.js
test/unit/src/http/proxy/format/templatize-test.js
test/unit/src/http/proxy/index-test.js
test/unit/src/http/proxy/read/_local-test.js
test/unit/src/http/proxy/read/_pretty-test.js
test/unit/src/http/proxy/read/_s3-test.js
test/unit/src/http/session/session-test.js

relates to architect/architect#1146

use `match` and `equals` instead of `ok` where possible in tape tests

---

src/tables/index.js
src/tables/sandbox.js
test/integration/tables-nuschool-test.js
test/mock/mock-arc
test/unit/src/tables/sandbox-test.js

- Process table names once
- allow for dependency injection for unit testing
- remove a fair amount of nesting
- ensure similarly named tables return the correct full table name
- add some more tests
Thanks again!

refactor tables sandbox()

---

_changelog.md
package.json
src/discovery/index.js
src/events/publish.js
src/index.js
src/lib/get-ports.js
src/tables/dynamo.js
test/integration/static-fingerprinted-test.js
test/integration/static-plain-test.js
test/integration/tables-test.js
test/unit/src/discovery/index-test.js
test/unit/src/events/publish-test.js
test/unit/src/events/subscribe-test.js
test/unit/src/http/async/index-req-test.js
test/unit/src/http/async/index-res-test.js
test/unit/src/http/http-req-test.js
test/unit/src/http/http-res-test.js
test/unit/src/http/session/session-test.js
test/unit/src/queues/publish-test.js
test/unit/src/queues/subscribe-test.js
test/unit/src/static/index-test.js

Enable Functions v5 to be used as a bare module in test suites without setting env vars

---

_changelog.md
package.json
src/discovery/index.js
src/events/publish.js
src/tables/dynamo.js
src/tables/factory.js
src/ws/index.js
test/unit/src/discovery/index-test.js
test/unit/src/tables/dynamo-test.js

Retire `aws-sdk-mock` (84.8MB) for ~15 lines of code
Thanks again!

Deep require `aws-sdk` deps for a potentially large cold start perf boost

---

package.json
src/events/index.js
types/events.d.ts
types/events.test-d.ts
types/http.d.ts
types/index.d.ts
types/static.d.ts
types/tables.d.ts
types/tables.test-d.ts
types/tsconfig.json
types/tslint.json
types/util.d.ts
types/ws.d.ts

As discussed in https://github.com/orgs/architect/discussions/1346, this is the beginnings of adding stronger typing to the library. For now it's just the `tables` module, so I can get some feedback, and adjust the approach as needed.
Usage of these types would look something like this:
```ts
import arc from "@architect/functions";
type NoteTable = {
pk: string;
sk: string;
title: string;
body: string;
};
type UserTable = {
pk: string;
email: string;
};
type MyTables = {
note: NoteTable;
user: UserTable;
};
async function testingOutTheTypes() {
const db = await arc.tables<MyTables>();
// ❌ no such table
await db.blah.delete();
// ❌ no such attribute
await db.note.delete({ blah: 'blah' });
// ✅
await db.note.delete({ pk: 'yay' });
};
```
Thoughts so far?

Add type definitions

---

types/tables.d.ts
types/tables.test-d.ts

This is a fix for the new types in the current RC, which I implemented and @tbeseda merged.
I previously had `put` returning `{}`, which is incorrect. `put` actually [returns whatever you pass into it](https://github.com/architect/functions/blob/main/src/tables/factory.js#L59). This is now fixed.

Fix return type on arc.tables.name.put

---

_changelog.md
src/ws/index.js
types/ws.d.ts

`ws._api` starts undefined and the only way to instantiate api is to make an api call. This replaces the export with a getter that calls `instantiateAPI()` so it's always there when you ask for it and now there doesn't need to be a method to instantiate it.
An alternative would be to make a method that returns the api (and maybe eventually remove `ws._api`).
I notice the [docs are wrong](https://github.com/architect/arc.codes/blob/main/src/views/docs/en/reference/runtime-helpers/node.js.md#arcws_api) (the types are right) and will fix that however this one lands.

fix: ws._api needs to be initialized but there's no method to do it

---

src/http/helpers/binary-types.js

Brought in line with the changes we did in the Remix repo:
- https://github.com/remix-run/remix/blob/534e1ec071f17654a4db8622e30d6ff70548ce26/packages/remix-architect/binaryTypes.ts#L23
- https://github.com/remix-run/remix/blob/534e1ec071f17654a4db8622e30d6ff70548ce26/packages/remix-architect/binaryTypes.ts#L37-L38

fix(http): update `binaryTypes` array

---

src/http/_res-fmt.js

Hello,
While browsing the remix project, I noticed that the control of the "Content-Type" header which allows to know if the body is binary could be improved. It is also possible to apply this change in this project.
Indeed, the check on the value of the header is done using an iteration on the array and a test for the presence of string with the Array.includes method. 
This implies a complexity of O(TypesCount*IncludesComplexity). It would be more efficient to use Set.has because the complexity would be O(1).
Related remix PR : https://github.com/remix-run/remix/pull/4761

perf(http) Improve IsBinary checking performance

---

package.json
types/http.d.ts
types/index.d.ts
types/index.test-d.ts
types/tables.d.ts

alternative to https://github.com/architect/functions/pull/550
Typings for new Architect Functions v7 features as well as some minor fixes for missing features in HTTPRequests and "middleware" return types.
Unfortunately, I don't think the JSDoc approach for a consumed library with complex types is sustainable right now. The TS lang server (used by most modern editors to parse _Javascript_ files) is inconsistent in how it interprets doc comments and bubbles those types to the end user/developer working with Arc.
So for now, I still recommend keeping a types/ dir with exported types written in TS and tested with a simple .test-d.ts file.

v7 types update

---

types/events.d.ts

Returning `unknown` from `events.subscribe`, as the types do today, sucks if you're writing tests:
This PR attempts to address this by tweaking the return type of `subscribe`, which is conditional based on what kind of event handler function you pass into `subscribe`:
1. [If you pass an async function, `subscribe` returns an async function](https://github.com/architect/functions/blob/main/src/events/subscribe.js#L25-L26).
2. [If you pass it a regular function that accepts two parameters, the second parameter being a callback, it returns a regular function that takes three parameters, the last being a callback too](https://github.com/architect/functions/blob/main/src/events/subscribe.js#L44-L45).
With these changes, now my tests are tidier with less IDE complaints. With an async handler …

Fix events.subscribe types: returns either an async or promise function

---

types/tables.d.ts

The documentation for the `scan()` and `scanAll()` methods (https://arc.codes/docs/en/reference/runtime-helpers/node.js#instance-methods) say that the parameters are optional. However, this isn't reflected in the type definitions. This PR fixes that.

Mark `scan()` and `scanAll()` parameters as optional

---

src/http/helpers/body-parser.js
test/unit/src/http/helpers/body-parser-test.js

I recently upgraded an app using @architect/functions from ^3.14.1 to ^8.1.6 and ran into an error parsing the body from some client requests.
It turned out that there was some client code sending an invalid content type header, formatting it the same as http accept, and including two comma-separated mime types, application/json and text/plain, which I know is just wrong, but the way the body parser handled this was to consider the request to be both json and plain text and then blow up when parsing the body as plain text, with the error below...
```json
{
"errorType": "TypeError",
"errorMessage": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
"code": "ERR_INVALID_ARG_TYPE",
"stack": [ …
```

fix: body parser behaviour when multiple `Content-Type` present in HTTP request

---

package.json
readme.md
src/http/csrf/create.js
src/http/csrf/verify.js
src/http/index.js
test/unit/src/http/csrf/create-and-verify-test.js

first pass at adding basic csrf tokens

---

types/tables.d.ts

This adds TablesOptions to the ArcTables types. This should surface the options to users that need to drop down into `tables._client` and need to set up the options.

Add TablesOptions type to tables.d.ts
